#!/usr/bin/env node
/* =====================================================================
   SEO BLOCK INSTALLER

   Writes one generated block into the <head> of every page except the
   scanner, which was hand-tuned and is left alone.

   WHAT IT WRITES, and why each part is there:

   · Open Graph and Twitter card tags. Only index.html had them. Every
     other page — including all five guides — rendered as a bare link
     when anyone pasted it into X, Telegram, Discord or Slack, which is
     exactly where this audience talks. This is the cheapest traffic
     fix available and it was simply missing.

   · Article structured data, with a real published and modified date
     taken from git rather than typed by hand. Crypto safety advice is
     what Google classifies as "your money or your life" content and
     holds to a higher bar: who wrote this, when, and has it been kept
     up to date. The site could answer all three and was telling nobody.

   · A breadcrumb trail. Home → Guides → this guide. Breadcrumbs still
     appear in search results, and they cost nothing.

   WHAT IT DOES NOT DO. No keyword stuffing, no FAQ markup on pages that
   are not FAQs, no invented ratings or review counts. Schema.org markup
   that misrepresents a page is a manual-action risk, and on a site
   whose entire pitch is that it does not overstate what it knows, it
   would also just be embarrassing.

   Run:  node seo.js          (rewrites the block in place)
         node seo.js --check  (exit 1 if any page is out of date)
   ===================================================================== */

const fs = require('fs');
const path = require('path');
const { execSync } = require('child_process');

const SITE = 'https://savesavesavesave.xyz';
const AUTHOR = 'Stefan Tsezarov';
const OG_IMAGE = SITE + '/og-image.png';

const BEGIN = '<!-- SEO:BEGIN — generated by seo.js, do not edit by hand -->';
const END = '<!-- SEO:END -->';

// index.html is deliberately absent: its head is hand-written, carries
// the SoftwareApplication graph, and is the one page where a generator
// stomping on careful work would cost more than it saves.
const PAGES = {
  'guides.html':             { type: 'collection', crumb: 'Guides' },
  'whitepaper.html':         { type: 'page',    crumb: 'Before You Act' },
  'technical-appendix.html': { type: 'article', crumb: 'Technical Transparency', section: 'Transparency' },
  'honeypot-tokens.html':    { type: 'guide',   crumb: 'Honeypot tokens', section: 'Token risk' },
  'invisible-characters.html': { type: 'guide', crumb: 'Invisible characters', section: 'Message risk' },
  'prompt-injection.html':   { type: 'guide',   crumb: 'Prompt injection', section: 'Message risk' },
  'seed-phrase-phishing.html': { type: 'guide', crumb: 'Seed-phrase phishing', section: 'Message risk' },
  'disguised-links.html':    { type: 'guide',   crumb: 'Disguised links', section: 'Link risk' },
  'privacy.html':            { type: 'page',    crumb: 'Privacy' },
  'terms.html':              { type: 'page',    crumb: 'Terms' },
};

const GUIDE_ORDER = [
  'honeypot-tokens.html', 'invisible-characters.html', 'prompt-injection.html',
  'seed-phrase-phishing.html', 'disguised-links.html',
];

// ---------------------------------------------------------------------
function read(f) { return fs.readFileSync(path.join(__dirname, f), 'utf8'); }
function pick(re, s, what, f) {
  const m = s.match(re);
  if (!m) throw new Error(f + ': could not find ' + what + '. Refusing to guess.');
  return m[1].trim();
}
function decode(s) {
  return s.replace(/&amp;/g, '&').replace(/&lt;/g, '<').replace(/&gt;/g, '>')
          .replace(/&quot;/g, '"').replace(/&#39;/g, "'").replace(/&nbsp;/g, ' ');
}
function attr(s) {
  return String(s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');
}

// Dates come from git, never from a hand-typed string that drifts.
//
// AND THEY TRACK THE WORDS, NOT THE FILE. The obvious version of this
// used the last commit that touched the file, which would have stamped
// every page on the site with the same "updated" date the moment a
// build script rewrote a meta tag. That is not what a reader takes
// "updated" to mean, and a site whose modification dates all move
// together is telling a search engine something untrue about itself.
//
// So each commit's copy of the page is reduced to its readable text,
// and the modified date is the last commit where that text actually
// changed. Rewriting a tag does not count. Rewriting a paragraph does.
function contentSig(text) {
  const body = String(text)
    .replace(/<head[\s\S]*?<\/head>/i, '')
    // The byline is metadata about the article, not the article. Leaving
    // it in made this tool perturb its own input: writing a date changed
    // the text, which changed the date, which changed the text. Stripping
    // it means a rewritten byline never counts as a content edit.
    .replace(/<p class="eyebrow">[\s\S]*?<\/p>/i, '')
    .replace(/<script[\s\S]*?<\/script>/gi, '')
    .replace(/<style[\s\S]*?<\/style>/gi, '')
    .replace(/<!--[\s\S]*?-->/g, '')
    .replace(/<[^>]+>/g, ' ');
  return body.replace(/\s+/g, ' ').trim();
}

// A shallow clone has no history to read. GitHub's checkout action makes
// one by default (a single commit), and in it every page looks as if it
// was published and last changed on the day of the newest commit. Those
// dates would be wrong and written with full confidence, so stop instead
// and say why. (No git at all is different: gitDates falls back to today.)
let historyChecked = false;
function requireFullHistory() {
  if (historyChecked) return;
  let shallow = 'false';
  try {
    shallow = execSync('git rev-parse --is-shallow-repository',
      { cwd: __dirname, encoding: 'utf8', stdio: ['ignore', 'pipe', 'ignore'] }).trim();
  } catch (_) { historyChecked = true; return; }
  if (shallow === 'true') {
    console.error('seo.js cannot date pages from a shallow clone: the git history is missing. '
      + 'In GitHub Actions, check out with fetch-depth: 0.');
    process.exit(2);
  }
  historyChecked = true;
}

const dateCache = new Map();
function gitDates(f) {
  if (dateCache.has(f)) return dateCache.get(f);
  requireFullHistory();
  const today = new Date().toISOString().slice(0, 10);
  let out = { published: today, modified: today };
  try {
    const shas = execSync(`git log --format=%H -- "${f}"`, { cwd: __dirname, encoding: 'utf8' })
      .trim().split('\n').filter(Boolean);
    if (shas.length) {
      out.published = execSync(`git log -1 --format=%ad --date=short ${shas[shas.length - 1]}`,
        { cwd: __dirname, encoding: 'utf8' }).trim();

      // Walk back from the newest commit until the readable text differs.
      // The working tree is the current state; compare against each
      // committed version in turn.
      let current = contentSig(read(f));
      let modified = execSync(`git log -1 --format=%ad --date=short ${shas[0]}`,
        { cwd: __dirname, encoding: 'utf8' }).trim();
      for (let i = 0; i < shas.length && i < 60; i++) {
        let older = '';
        try { older = contentSig(execSync(`git show ${shas[i]}:"${f}"`, { cwd: __dirname, encoding: 'utf8', maxBuffer: 32 * 1024 * 1024 })); }
        catch (_) { break; }
        if (older !== current) {
          // shas[i] is older than the change, so the change landed in
          // the commit one step newer — or in the working tree.
          modified = i === 0 ? today
            : execSync(`git log -1 --format=%ad --date=short ${shas[i - 1]}`,
                { cwd: __dirname, encoding: 'utf8' }).trim();
          break;
        }
        modified = execSync(`git log -1 --format=%ad --date=short ${shas[i]}`,
          { cwd: __dirname, encoding: 'utf8' }).trim();
      }
      out.modified = modified < out.published ? out.published : modified;
    }
  } catch (_) { /* no git, or file untracked: today is the honest answer */ }
  dateCache.set(f, out);
  return out;
}

// Counted off the same signature the dates use, so writing a byline does
// not change the word count, which would change the block, which would
// make a second run rewrite everything again.
function words(html) { return contentSig(html).split(/\s+/).filter(Boolean).length; }

// A description written for a human reading a search result: the first
// sentence has to survive truncation at about 155 characters, so the
// full text is kept for the social card and a trimmed one is used for
// the snippet tags.
function short(desc, limit) {
  const d = decode(desc);
  if (d.length <= limit) return d;
  const cut = d.slice(0, limit);
  const stop = Math.max(cut.lastIndexOf('. '), cut.lastIndexOf(' — '), cut.lastIndexOf(', '));
  return (stop > limit * 0.5 ? cut.slice(0, stop + 1) : cut.replace(/\s+\S*$/, '') + '…').trim();
}

function ld(obj) { return JSON.stringify(obj, null, 2); }

// "20 September 2026", not "2026-09-20". The machine-readable form is
// already in the datetime attribute; the visible one is for a reader.
const MONTHS = ['January','February','March','April','May','June','July',
                'August','September','October','November','December'];
function human(iso) {
  const m = /^(\d{4})-(\d{2})-(\d{2})$/.exec(iso);
  if (!m) return iso;
  return Number(m[3]) + ' ' + MONTHS[Number(m[2]) - 1] + ' ' + m[1];
}

function buildBlock(file, cfg, all) {
  const html = read(file);
  const rawTitle = pick(/<title>([\s\S]*?)<\/title>/, html, '<title>', file);
  const rawDesc = pick(/<meta name="description" content="([\s\S]*?)"\s*\/?>/, html, 'meta description', file);
  const canonical = pick(/<link rel="canonical" href="([^"]+)"/, html, 'canonical', file);
  const h1 = decode(pick(/<h1[^>]*>([\s\S]*?)<\/h1>/, html, '<h1>', file).replace(/<[^>]+>/g, ''));
  const title = decode(rawTitle);
  const desc = decode(rawDesc);
  const { published, modified } = gitDates(file);
  const socialTitle = title.replace(/\s+—\s+SaveSaveSaveSave\s*$/, '');

  const isArticle = cfg.type === 'guide' || cfg.type === 'article';
  const ogType = isArticle ? 'article' : 'website';

  const crumbs = [
    { '@type': 'ListItem', position: 1, name: 'Scanner', item: SITE + '/' },
  ];
  if (cfg.type === 'guide') {
    crumbs.push({ '@type': 'ListItem', position: 2, name: 'Guides', item: SITE + '/guides' });
    crumbs.push({ '@type': 'ListItem', position: 3, name: cfg.crumb });
  } else {
    crumbs.push({ '@type': 'ListItem', position: 2, name: cfg.crumb });
  }

  const publisher = {
    '@type': 'Organization',
    '@id': SITE + '/#publisher',
    name: 'SaveSaveSaveSave',
    url: SITE + '/',
    logo: { '@type': 'ImageObject', url: SITE + '/apple-touch-icon.png' },
  };
  const author = {
    '@type': 'Person',
    '@id': SITE + '/#author',
    name: AUTHOR,
    url: SITE + '/whitepaper',
  };

  const graph = [];

  if (isArticle) {
    graph.push({
      '@type': 'TechArticle',
      '@id': canonical + '#article',
      headline: h1.slice(0, 110),
      alternativeHeadline: socialTitle,
      name: socialTitle,
      description: desc,
      url: canonical,
      mainEntityOfPage: { '@type': 'WebPage', '@id': canonical },
      datePublished: published,
      dateModified: modified,
      author, publisher,
      inLanguage: 'en',
      wordCount: words(html),
      isAccessibleForFree: true,
      articleSection: cfg.section || 'Security',
      isPartOf: { '@type': 'WebSite', '@id': SITE + '/#website' },
    });
  } else if (cfg.type === 'collection') {
    graph.push({
      '@type': 'CollectionPage',
      '@id': canonical + '#page',
      name: socialTitle,
      description: desc,
      url: canonical,
      inLanguage: 'en',
      publisher,
      isPartOf: { '@type': 'WebSite', '@id': SITE + '/#website' },
      mainEntity: {
        '@type': 'ItemList',
        itemListOrder: 'https://schema.org/ItemListUnordered',
        numberOfItems: GUIDE_ORDER.length,
        itemListElement: GUIDE_ORDER.map((g, i) => ({
          '@type': 'ListItem',
          position: i + 1,
          url: SITE + '/' + g.replace(/\.html$/, ''),
          name: decode((all[g] || '').replace(/\s+—\s+SaveSaveSaveSave\s*$/, '')),
        })),
      },
    });
  } else {
    graph.push({
      '@type': 'WebPage',
      '@id': canonical + '#page',
      name: socialTitle,
      description: desc,
      url: canonical,
      inLanguage: 'en',
      datePublished: published,
      dateModified: modified,
      publisher,
      isPartOf: { '@type': 'WebSite', '@id': SITE + '/#website' },
    });
  }

  graph.push({ '@type': 'BreadcrumbList', '@id': canonical + '#breadcrumb', itemListElement: crumbs });

  const snippet = short(desc, 158);

  const lines = [
    BEGIN,
    '<meta property="og:type" content="' + ogType + '">',
    '<meta property="og:site_name" content="SaveSaveSaveSave">',
    '<meta property="og:locale" content="en">',
    '<meta property="og:url" content="' + canonical + '">',
    '<meta property="og:title" content="' + attr(socialTitle) + '">',
    '<meta property="og:description" content="' + attr(snippet) + '">',
    '<meta property="og:image" content="' + OG_IMAGE + '">',
    '<meta property="og:image:width" content="1200">',
    '<meta property="og:image:height" content="630">',
    '<meta property="og:image:alt" content="SaveSaveSaveSave — free risk screening for crypto messages and addresses">',
  ];
  if (isArticle) {
    lines.push('<meta property="article:published_time" content="' + published + '">');
    lines.push('<meta property="article:modified_time" content="' + modified + '">');
    lines.push('<meta property="article:author" content="' + attr(AUTHOR) + '">');
    if (cfg.section) lines.push('<meta property="article:section" content="' + attr(cfg.section) + '">');
  }
  lines.push('<meta name="twitter:card" content="summary_large_image">');
  lines.push('<meta name="twitter:title" content="' + attr(socialTitle) + '">');
  lines.push('<meta name="twitter:description" content="' + attr(snippet) + '">');
  lines.push('<meta name="twitter:image" content="' + OG_IMAGE + '">');
  lines.push('<script type="application/ld+json">');
  lines.push(ld({ '@context': 'https://schema.org', '@graph': graph }));
  lines.push('</script>');
  lines.push(END);

  return lines.join('\n');
}

// The eyebrow already read "Guide · Link risk · September 2026". This
// makes that date machine-readable and puts a name on the article.
// A named author and a date a crawler can parse are the two cheapest
// credibility signals there are, and the page had neither.
function upgradeByline(html, file, published, modified) {
  const m = html.match(/<p class="eyebrow">([\s\S]*?)<\/p>/);
  if (!m) return html;
  if (/<time /.test(m[1])) return html;   // already done
  const text = m[1].trim();
  const dm = text.match(/([A-Z][a-z]+ \d{4})\s*$/);
  if (!dm) return html;
  const stamped = text.replace(/([A-Z][a-z]+ \d{4})\s*$/,
    '<time datetime="' + published + '">' + dm[1] + '</time>')
    + ' · by ' + AUTHOR
    + (modified !== published ? ' · updated <time datetime="' + modified + '">' + human(modified) + '</time>' : '');
  return html.replace(m[0], '<p class="eyebrow">' + stamped + '</p>');
}

// ---------------------------------------------------------------------
const checkOnly = process.argv.includes('--check');
const titles = {};
Object.keys(PAGES).forEach(f => {
  const s = read(f);
  const t = s.match(/<title>([\s\S]*?)<\/title>/);
  titles[f] = t ? t[1].trim() : f;
});

let changed = 0, stale = [];
Object.entries(PAGES).forEach(([file, cfg]) => {
  let html = read(file);
  const block = buildBlock(file, cfg, titles);

  if (cfg.type === 'guide') {
    const { published, modified } = gitDates(file);
    const next = upgradeByline(html, file, published, modified);
    if (next !== html) { html = next; }
  }

  const has = html.indexOf(BEGIN);
  let out;
  if (has !== -1) {
    const end = html.indexOf(END, has);
    if (end === -1) throw new Error(file + ': SEO:BEGIN with no SEO:END. Refusing to guess where the block stops.');
    out = html.slice(0, has) + block + html.slice(end + END.length);
  } else {
    // Anchored to the canonical tag, which every page has and which is
    // already verified against what the deploy really serves.
    const anchor = html.match(/<link rel="canonical" href="[^"]+"\s*\/?>/);
    if (!anchor) throw new Error(file + ': no canonical tag to anchor the block to.');
    out = html.replace(anchor[0], anchor[0] + '\n' + block);
  }

  if (out !== read(file)) {
    stale.push(file);
    if (!checkOnly) { fs.writeFileSync(path.join(__dirname, file), out); changed++; }
  }
  console.log('  ' + (stale.includes(file) ? (checkOnly ? 'STALE ' : 'wrote ') : 'clean ') + file.padEnd(28)
    + cfg.type.padEnd(11) + gitDates(file).published + ' → ' + gitDates(file).modified);
});

console.log('');
if (checkOnly) {
  if (stale.length) {
    console.log(stale.length + ' page(s) out of date. Run: node seo.js');
    process.exit(1);
  }
  console.log('All ' + Object.keys(PAGES).length + ' pages carry an up-to-date SEO block.');
} else {
  console.log(changed + ' page(s) rewritten, ' + (Object.keys(PAGES).length - changed) + ' already current.');
  console.log('index.html is deliberately not managed here — its head is hand-written.');
}
