// Generated by agent/build.js from index.html. Do not edit.
function compareAddresses(a, b){
  a = String(a || '').trim(); b = String(b || '').trim();
  if(!a || !b) return { state: 'empty' };
  const hex = /^0x[0-9a-fA-F]{40}$/;
  const fold = hex.test(a) && hex.test(b);
  const x = fold ? a.toLowerCase() : a, y = fold ? b.toLowerCase() : b;
  if(x === y) return { state: a === b ? 'same' : 'same-case', length: a.length };
  if(x.length !== y.length) return { state: 'length' };
  const start = fold ? 2 : 0;
  const diffs = [];
  for(let i = 0; i < x.length; i++) if(x[i] !== y[i]) diffs.push(i);
  let prefix = 0; while(start + prefix < x.length && x[start + prefix] === y[start + prefix]) prefix++;
  let suffix = 0; while(suffix < x.length && x[x.length - 1 - suffix] === y[y.length - 1 - suffix]) suffix++;
  return { state: 'different', diffs, prefix, suffix, length: x.length, lookalike: prefix >= 3 && suffix >= 3 };
}

module.exports = { compareAddresses };
