#!/usr/bin/env node
// Copies the site's engine into agent/lib so the npm package and the MCP
// server run exactly the code the website runs. `--check` fails if lib/ is
// stale (run in CI), so the agent tools can never drift from the site.
const fs = require('fs');
const path = require('path');
const root = path.join(__dirname, '..');
const lib = path.join(__dirname, 'lib');
const out = {};
out['core.js'] = fs.readFileSync(path.join(root, 'core.js'), 'utf8');
out['promptscan.js'] = fs.readFileSync(path.join(root, 'promptscan.js'), 'utf8');
const page = fs.readFileSync(path.join(root, 'index.html'), 'utf8');
const a = page.indexOf('function compareAddresses('), b = page.indexOf('function twinRow(');
if (a < 0 || b < a) { console.error('FAIL: compareAddresses not found in index.html'); process.exit(1); }
// Drop the whole comment block that introduces twinRow, not just its last
// line, so no half-sentence is left dangling in the generated file.
out['compare.js'] = '// Generated by agent/build.js from index.html. Do not edit.\n'
  + page.slice(a, b).replace(/(?:[ \t]*\/\/[^\n]*\n)+\s*$/, '') + '\nmodule.exports = { compareAddresses };\n';
const check = process.argv.includes('--check');
let stale = [];
for (const [f, src] of Object.entries(out)) {
  const p = path.join(lib, f);
  const cur = fs.existsSync(p) ? fs.readFileSync(p, 'utf8') : null;
  if (cur === src) continue;
  if (check) stale.push(f); else { fs.mkdirSync(lib, { recursive: true }); fs.writeFileSync(p, src); }
}
if (check && stale.length) { console.error('FAIL: agent/lib is out of date (' + stale.join(', ') + '). Run: node agent/build.js'); process.exit(1); }
console.log(check ? 'agent/lib matches the site engine.' : 'agent/lib written.');
